apiVersion: v1
kind: Service
metadata:
  name: {{ include "signalops.name" . }}-api
  labels:
    {{- include "signalops.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "signalops.name" . }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
